### ISSUE TITLE
Explanation of SheOS having 2m SYS

### ISSUE THREAD

**Issue by peteknowsai** [API-market/ore-bp-docs#15]
SheOS currently has over 2 million SYS that they were able to claim for BP rewards.  Given that SheOS didn't start producing blocks until 01-18-2019 their share should be close to 80k SYS.  

The number that SheOS has is closer to the total amount of SYS that ALL BPs would have been able to claim from the beginning.   

@apimdavid We need to understand the problem so we can correct and prevent in the future.

**Comment by apimdavid** [comment]
Started effort to extract all issue and transfer actions affecting producer account sheos21sheos: running filter-on = * and contracts-console = true on a full, non-producing node in production.

**Comment by apimdavid** [comment]
Now replaying all blocks back to the beginning on the full node. We should be able to get info on all actions executed in our chain's history once the replay is done later this evening 2/26

**Comment by apimdavid** [comment]
Progress: we have a detailed accounting of each transfer of SYS into ShEOS's account and the total precisely matches the amount they hold.  Still to be done: explain why these transfers were so large.
