### ISSUE TITLE
Test onboarding of new BP (including verifier)

### ISSUE THREAD

**Issue by peteknowsai** [API-market/ore-bp-docs#2]
@petemccarthy commented on [Wed Dec 19 2018](https://github.com/API-market/ore-bp/issues/3)

@petemccarthy commented on [Tue Dec 18 2018](https://github.com/API-market/ore-id/issues/256)

**Comment by apimdavid** [comment]
New BPs are being added successfully -- but nothing has yet been done about the Verifiers.
